# Welcome to Jekyll!
#

# Site settings
title: WaterMotion Studio
description: |
  Reflection of Imagination <br>
  <b> We work for nothing </b> <br>
  <b> Only the game and its audience </b> <br>
owner: WaterMotion Studio # or company name
first_published: 2021 # if migrating another site, the year of your first publish
email: watermotionstudio@gmail.com
baseurl: "/wm" # the subpath of your site, e.g. /blog
url: "http://watermotionstudio.github.io" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/watermotiongame
  #github: https://github.com/<username>
  #linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://www.facebook.com/WaterMotion-Studio-105283328527829
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: watermotiongames@gmail.com
  #flickr:
  instagram: https://www.instagram.com/watermotionstudio/
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  reddit: https://www.reddit.com/user/WaterMotionStudio
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
